import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/config/site";

// Only real, public, indexable marketing pages — never /dashboard/*,
// /login, /signup, or anything under /api. Kept as a flat literal list
// (not generated by walking the app directory) so a new authenticated
// or functional route can never accidentally end up here by default.
const PUBLIC_PATHS = [
  "",
  "/about",
  "/contact",
  "/blog",
  "/affiliates",
  "/api",
  "/legal/privacy",
  "/legal/terms",
  "/legal/cookies",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return PUBLIC_PATHS.map((path) => ({
    url: `${SITE_URL}${path}`,
    lastModified: now,
    changeFrequency: path === "" ? "weekly" : "monthly",
    priority: path === "" ? 1 : 0.6,
  }));
}
